### ISSUE TITLE
Exception thrown on billing page when installing through partners dashboard

### ISSUE THREAD

**Issue by RandomWeasel** [osiset/laravel-shopify#424]
## Expected Behavior

App should display billing screen

## Current Behavior

Error is thrown on /billing page

```
InvalidArgumentException
1 is not a valid value for this enum.

Osiset\ShopifyApp\Objects\Enums\PlanType::fromNative
:64
vendor/funeralzone/valueobjects/src/Enums/EnumTrait.php:64
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Installing the app (unlisted) through the shopify partner 'Test on demo store' functionality
2. Enter shop domain on login screen
3. Accept OAuth
4. In this case, I viewed the app by going to the app url via the 'apps' list on the store, but I expect it would happen with the standard redirect (this is not working correctly but has a separate issue).  The error message is shown on the app page within the shopify iframe, which is pointing to the `/billing` route

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

The app is set to billable, with 
`SHOPIFY_BILLING_ENABLED=true` in the env file (also tried with 1 as per docs), 
`'billing_enabled' => (bool) env('SHOPIFY_BILLING_ENABLED', true),` in the config file
and `->middleware(['auth.shopify', 'billable'])` on the home route

* Package Version: v11.1.0
* Laravel Version: v6.9.0
* PHP Version: v7.3.14 
* Using a toolset (Docker, Laradock, Vagrant, etc.): Docker with ngrok tunnel to access the app running locally - ngrok addresses for app url and authentication url are provided in app settings in shopify.  I have also tried adding the billing url in the redirection urls (not mentioned in the docs) but this makes no difference.

### Failure Logs

```[2020-03-20 11:22:47] local.ERROR: 1 is not a valid value for this enum. {"userId":8,"exception":"[object] (InvalidArgumentException(code: 0): 1 is not a valid value for this enum. at /home/rebound_connector/vendor/funeralzone/valueobjects/src/Enums/EnumTrait.php:64)
[stacktrace]
#0 /home/rebound_connector/vendor/osiset/laravel-shopify/src/ShopifyApp/Storage/Models/Plan.php(54): Osiset\\ShopifyApp\\Objects\\Enums\\PlanType::fromNative('1')
#1 /home/rebound_connector/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/GetPlanUrl.php(74): Osiset\\ShopifyApp\\Storage\\Models\\Plan->getType()
#2 /home/rebound_connector/vendor/osiset/laravel-shopify/src/ShopifyApp/Traits/BillingController.php(39): Osiset\\ShopifyApp\\Actions\\GetPlanUrl->__invoke(Object(Osiset\\ShopifyApp\\Objects\\Values\\ShopId), Object(Osiset\\ShopifyApp\\Objects\\Values\\NullablePlanId))
#3 [internal function]: Osiset\\ShopifyApp\\Http\\Controllers\\BillingController->index(NULL, Object(Osiset\\ShopifyApp\\Actions\\GetPlanUrl), Object(Osiset\\ShopifyApp\\Services\\ShopSession))
#4 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#6 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Osiset\\ShopifyApp\\Http\\Controllers\\BillingController), 'index')
#7 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#9 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/rebound_connector/vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Osiset\\ShopifyApp\\Http\\Middleware\\AuthShopify->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#27 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#28 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#29 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#30 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/rebound_connector/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/rebound_connector/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /home/rebound_connector/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 /home/rebound_connector/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}
"} ```

**Comment by osiset** [comment]
Thanks @RandomWeasel

Can you give me the SQL row data for the plan?

**Comment by osiset** [comment]
Based on the stack trace it seems your plan type is an int. If I remember, it needs to be an upcass string like "RECURRING" or "ONETIME"

**Comment by RandomWeasel** [comment]
@osiset spot-on, my plan type was set to 1.  Changed it and the issue is resolved :)

It looks like there's an update needed in the wiki https://github.com/osiset/laravel-shopify/wiki/Creating-a-Billable-App#creating-plans - the 'example setup' code snippet is correct, but the 'values' bullet points aren't
![image](https://user-images.githubusercontent.com/16453825/77166625-78b0e700-6aac-11ea-9742-f5fbd9ca2114.png)

**Comment by osiset** [comment]
@RandomWeasel Thanks, updated wiki!

**Comment by RandomWeasel** [comment]
Hey @osiset, should this read 'ONETIME'?  looks like there's a typo, it says 'ONTIME' :) 

![image](https://user-images.githubusercontent.com/16453825/77624178-50583b00-6f39-11ea-894d-45610148fbff.png)

**Comment by osiset** [comment]
Thanks!

**Comment by awebartisan** [comment]
Re-opening this issue as I am receiving exception for "ONETIME" value.

**Exception**: ONETIME is not a valid value for this enum.

**Note:** It doesn't throw exception for "RECURRING" value.

**Insert SQL below:**
```sql
INSERT INTO `plans` (`id`, `type`, `name`, `price`, `capped_amount`, `terms`, `trial_days`, `test`, `on_install`, `created_at`, `updated_at`) VALUES
('3', 'ONETIME', 'Plan name', '80.00', NULL, NULL, NULL, '1', '0', '2020-04-06 10:39:34', '2020-04-06 10:39:34');```

Currently trying my best to debug it but couldn't find any clue.

**Comment by osiset** [comment]
Will look into this... thanks

**Comment by awebartisan** [comment]
Just wanted to share my findings, flow of request is like below:

1. Starts from **index** method of **BillingControllerTrait.** 
```php
        // Get the plan URL for redirect
        $url = $getPlanUrl(
            $shopSession->getShop()->getId(),
            NullablePlanId::fromNative($plan)
        );
```

2. **__invoke** method of  **GetPlanUrl**. Below code snippet is responsible for getting the plan url.
```php
        $api = $shop->apiHelper()->createCharge(
            ChargeType::fromNative($plan->getType()->toNative()),
            $this->chargeHelper->details($plan, $shop)
        );
```
Now, `$plan->getType()->toNative()` returns **ONETIME** enum value, but **ChargeType** enum does not have the **ONETIME** value. Following are the enum values in ChargeType at the time of this writing.
```php
    public const RECURRING = 1;

    /**
     * Charge: One-time.
     *
     * @var int
     */
    public const CHARGE = 2;

    /**
     * Charge: Usage.
     *
     * @var int
     */
    public const USAGE = 3;

    /**
     * Charge: Credit.
     *
     * @var int
     */
    public const CREDIT = 4;
```
3. I went ahead and changed the **CHARGE** to **ONETIME**. But then  it won't work in **ApiHelper** class.
```php
    protected function chargeApiPath(ChargeType $chargeType): string
    {
        // Convert to API path
        $format = $chargeType->isSame(ChargeType::RECURRING()) ?
            '%s_application_charge' :
            'application_%s';

        return sprintf($format, strtolower($chargeType->toNative()));
    }
```
Because it will make it **application_onetime** instead of **application_charge**.

**Comment by awebartisan** [comment]
Hey @osiset , can you suggest a temporary fix for this when have the chance please? 

Thank you 🙏🏼

**Comment by osiset** [comment]
@awebartisan In reality, I would need to change ONETIME to CHARGE, its a legacy thing I left in to not break something.

What about this...

```php
    protected function chargeApiPath(ChargeType $chargeType): string
    {
        // Convert to API path
        if ($chargeType->isSame(ChargeType::RECURRING())) {
             $format =  '%s_application_charge';
        } else if ($chargeType->isSame(ChargeType::CHARGE)) {
             $format = 'application_charge';
        } else {
             $format = 'application_%s';
        }

        return sprintf($format, strtolower($chargeType->toNative()));
    }
```

**Comment by awebartisan** [comment]
Tried above snippet. 

`$chargeType->isSame(ChargeType::CHARGE)` is throwing error because `isSame` expects a ValueObject but `int` is given.

Tried changing it to `$chargeType->isSame(ChargeType::ONETIME())` because `ONETIME()` method corresponds to `CHARGE` enum value. Still facing the same error.

**ONETIME is not a valid value for this enum.**

Reason lies inside **GetPlanUrl**
```php
        $api = $shop->apiHelper()->createCharge(
            ChargeType::fromNative($plan->getType()->toNative()),
            $this->chargeHelper->details($plan, $shop)
        );
```
`$plan->getType()->toNative()` returns **ONETIME** but this value does not exist on **ChargeType** enum class. Therefore throws the exception. Let me know if I am missing something.

**Comment by osiset** [comment]
I have commited a solution for this which seems to work... I created an alias in the ChargeType enum for ONETIME to map it to CHARGE. Best I can do without breaking whats already being used.. somepoint down the road I'll revisit and fix it up properly.

**Comment by osiset** [comment]
@awebartisan 11.5.0 released with this alias fix, if it still persists, let me know ill reopen
