### ISSUE TITLE
Route [itp.ask] not defined.

### ISSUE THREAD

**Issue by parkourben99** [osiset/laravel-shopify#709]
### Context

* Package Version: v16.0.3
* Laravel Version: v8.28.1
* PHP Version: v7.4.10
* Using a toolset: Vapor - using docker image laravelphp/vapor:php74

Screenshot of `web.php`
![image](https://user-images.githubusercontent.com/7295774/109417377-57be7900-7a13-11eb-80be-22bbd651709a.png)

I've had this error ~70 times in the last 2 weeks.

I'm not sure that it matters but 67% of the time the user is using Safari.

![image](https://user-images.githubusercontent.com/7295774/109417621-5477bd00-7a14-11eb-8190-86d4ab9f75ac.png)

### Failure Logs

Stack trace 
```
Symfony\Component\Routing\Exception\RouteNotFoundException: Route [itp.ask] not defined.
#60 /vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(429): Illuminate\Routing\UrlGenerator::route
#59 /vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(176): Illuminate\Routing\Redirector::route
#58 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Support\Facades\Facade::__callStatic
#57 /vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/ITP.php(77): Osiset\ShopifyApp\Http\Middleware\ITP::ask
#56 /vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/ITP.php(39): Osiset\ShopifyApp\Http\Middleware\ITP::handle
#55 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#54 /vendor/osiset/laravel-shopify/src/ShopifyApp/Http/Middleware/AuthShopify.php(96): Osiset\ShopifyApp\Http\Middleware\AuthShopify::handle
#53 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#52 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Routing\Middleware\SubstituteBindings::handle
#51 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#50 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#49 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#48 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#47 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#46 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Session\Middleware\StartSession::handleStatefulRequest
#45 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession::handle
#44 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#43 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Cookie\Middleware\EncryptCookies::handle
#40 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#39 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#38 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Router::runRouteWithinStack
#37 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router::runRoute
#36 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router::dispatchToRoute
#35 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router::dispatch
#34 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#32 /vendor/laravel/vapor-core/src/Http/Middleware/ServeStaticAssets.php(21): Laravel\Vapor\Http\Middleware\ServeStaticAssets::handle
#31 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#30 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#29 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#26 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
#25 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#24 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::handle
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#22 /vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Fruitcake\Cors\HandleCors::handle
#21 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#20 /vendor/fideloper/proxy/src/TrustProxies.php(57): Fideloper\Proxy\TrustProxies::handle
#19 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#18 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(46): Sentry\Laravel\Tracing\Middleware::handle
#17 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#16 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#15 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#14 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel::handle
#13 /vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(151): Laravel\Vapor\Runtime\HttpKernel::Laravel\Vapor\Runtime\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#11 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureBinaryEncoding.php(19): Laravel\Vapor\Runtime\Http\Middleware\EnsureBinaryEncoding::handle
#10 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#9 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureVanityUrlIsNotIndexed.php(16): Laravel\Vapor\Runtime\Http\Middleware\EnsureVanityUrlIsNotIndexed::handle
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#7 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/RedirectStaticAssets.php(30): Laravel\Vapor\Runtime\Http\Middleware\RedirectStaticAssets::handle
#6 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#5 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureOnNakedDomain.php(39): Laravel\Vapor\Runtime\Http\Middleware\EnsureOnNakedDomain::handle
#4 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#2 /vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(152): Laravel\Vapor\Runtime\HttpKernel::sendRequest
#1 /vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(65): Laravel\Vapor\Runtime\HttpKernel::handle
#0 /httpHandler.php(55): null
```

**Comment by osiset** [comment]
Route is defined, not sure what else I can do here.

```php
    if (registerPackageRoute('itp.ask', $manualRoutes)) {
        Route::get('/itp/ask', 'Osiset\ShopifyApp\Http\Controllers\ItpController@ask')
            ->name(getShopifyConfig('route_names.itp.ask'));
    }
```

Thats lines 59-62 of routes/shopify.php.

**Comment by parkourben99** [comment]
I'm confused how it is even happening.

**Comment by osiset** [comment]
Given its happening for some requests and not others... then either registerPackageRoute may be failing due to either config or environment variables not being available for some reason on these requests OR the package routes are not registering in time.

Maybe try making it a manual route?

`SHOPIFY_MANUAL_ROUTES=itp.ask`

Then open `web.php` and add:

```php
Route::get('/itp/ask', 'Osiset\ShopifyApp\Http\Controllers\ItpController@ask')
            ->middleware(['itp'])
            ->name('itp.ask');
```

See if it solves the issue.

**Comment by parkourben99** [comment]
I think I have found the problem. It appears I did not update the config file when upgrading versions. Will close this issue. Thanks
