### ISSUE TITLE
WebHook issue for APP_UNINSTALL

### ISSUE THREAD

**Issue by brucelee90** [osiset/laravel-shopify#945]
For some reason the webhook APP_UNINSTALL keeps failing to get registered on app install.

my shopify-app.php looks as follows:

```
...
    'webhooks' =>
    [
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'APP_UNINSTALLED'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', 'appname.myshopify.com/webhook/app-uninstalled')
        ],
    ],

...
```

Whenever I install the app on any store, I get a failed job.

This is the error of the failed job:

```bash
GuzzleHttp\Exception\ClientException: Client error: `POST https://l4-sample-app.myshopify.com/admin/webhooks.json` resulted in a `422 Unprocessable Entity` response:
{"errors":{"topic":["Invalid topic specified: APP_UNINSTALLED. Does it exist? Is there a missing access scope? Topics al (truncated...)
 in /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/basic-shopify-api/src/Clients/Rest.php(135): GuzzleHttp\Client->request('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#11 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/basic-shopify-api/src/Clients/Rest.php(147): Osiset\BasicShopifyAPI\Clients\Rest->Osiset\BasicShopifyAPI\Clients\{closure}()
#12 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/basic-shopify-api/src/BasicShopifyAPI.php(411): Osiset\BasicShopifyAPI\Clients\Rest->request('POST', '/admin/webhooks...', Array, Array, true)
#13 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php(439): Osiset\BasicShopifyAPI\BasicShopifyAPI->rest('POST', '/admin/webhooks...', Array)
#14 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php(362): Osiset\ShopifyApp\Services\ApiHelper->doRequest(Object(Osiset\ShopifyApp\Objects\Enums\ApiMethod), '/admin/webhooks...', Array)
#15 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/CreateWebhooks.php(77): Osiset\ShopifyApp\Services\ApiHelper->createWebhook(Array)
#16 [internal function]: Osiset\ShopifyApp\Actions\CreateWebhooks->__invoke(Object(Osiset\ShopifyApp\Objects\Values\ShopId), Array)
#17 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Messaging/Jobs/WebhookInstaller.php(63): call_user_func(Object(Osiset\ShopifyApp\Actions\CreateWebhooks), Object(Osiset\ShopifyApp\Objects\Values\ShopId), Array)
#18 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller->handle(Object(Osiset\ShopifyApp\Actions\CreateWebhooks))
#19 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#21 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#22 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#24 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#25 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#26 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller), false)
#28 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#29 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#30 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#32 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#33 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(414): Illuminate\Queue\Jobs\Job->fire()
#34 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(364): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#35 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(315): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#36 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#37 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#38 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#39 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#40 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#41 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#42 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#43 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#44 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Command/Command.php(288): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#45 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#46 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Application.php(974): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#51 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#52 {main}

Next Osiset\ShopifyApp\Exceptions\ApiException: Unknown error in /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php:442
Stack trace:
#0 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Services/ApiHelper.php(362): Osiset\ShopifyApp\Services\ApiHelper->doRequest(Object(Osiset\ShopifyApp\Objects\Enums\ApiMethod), '/admin/webhooks...', Array)
#1 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Actions/CreateWebhooks.php(77): Osiset\ShopifyApp\Services\ApiHelper->createWebhook(Array)
#2 [internal function]: Osiset\ShopifyApp\Actions\CreateWebhooks->__invoke(Object(Osiset\ShopifyApp\Objects\Values\ShopId), Array)
#3 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/osiset/laravel-shopify/src/ShopifyApp/Messaging/Jobs/WebhookInstaller.php(63): call_user_func(Object(Osiset\ShopifyApp\Actions\CreateWebhooks), Object(Osiset\ShopifyApp\Objects\Values\ShopId), Array)
#4 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller->handle(Object(Osiset\ShopifyApp\Actions\CreateWebhooks))
#5 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#7 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#10 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#11 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#12 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller), false)
#14 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#15 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#16 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Osiset\ShopifyApp\Messaging\Jobs\WebhookInstaller))
#18 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#19 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(414): Illuminate\Queue\Jobs\Job->fire()
#20 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(364): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#21 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(315): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#22 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->runNextJob('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#23 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#24 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#25 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#27 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#28 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#29 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#30 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Command/Command.php(288): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Application.php(974): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /Users/leeklopfers/projex/laravel/laravel-boilerplate-shopify/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}
```

I followed the wiki and published the AppUninstalled job with p`hp artisan vendor:publish --tag=shopify-jobs`. I can also see the Job AppUninstalledJob within my app/Jobs directory.

I also migrated after publishing the job, but it said "nothing to migrate".

I wonder why the error message of the failed job says it cannot find "APP_UNINSTALL"

**Comment by enmaboya** [comment]
config/shopify-app.php:

    'webhooks' => [
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'app/uninstalled'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', env('APP_URL').'webhook/app-uninstalled')

        ],
        [
            'topic' => env('SHOPIFY_WEBHOOK_1_TOPIC', 'orders/create'),
            'address' => env('SHOPIFY_WEBHOOK_1_ADDRESS', env('APP_URL').'webhook/orders-create')
        ]
    ],



.env:
APP_URL=https://837752639f9e.ngrok.io**/**

**Comment by brucelee90** [comment]
Thank you, this way the job doesn't fail anymore.

But if I uninstall the app, the store is not being removed from the database. How can I verify that the webhook is registered correctly?

If I test the route with Postman I get an 401 error, so that indicates the route exists. I'm running out of ideas how to test if the webhook is correctly triggered by shopify, or if the problem lies within my app.

**Comment by LonnyX** [comment]
@brucelee90 The record should not be removed from the database as long as you are using the default behavior. It should only be sofdeleted (the field deleted_at should be filled)

**Comment by brucelee90** [comment]
@LonnyX, Thank you for the explanation. I just checked it and for some reason the field deleted_at is not being filled upon uninstallation.

Is there any way to debug this? I would like to know if the problem is at my app's end or if it's at shopify's end. I really don't know what is causing this error.

**Comment by LonnyX** [comment]
This field will not be filled locally because Shopify doesn't know your host, it's not accessible publicly, you can use `valet share` to test it. You can also test it directly on your server, if the webhook are correctly configured (check the docs on wiki page) everything should works fine

**Comment by brucelee90** [comment]
Thank you very much! I Just deployed my app to heroku and everything works just fine!
